### ISSUE TITLE
请问怎么编译啊？

### ISSUE THREAD

**Issue by SoulLinksIly** [ohdarling/AirCube#1]
小白想做一个这个东西，想知道用什么软件，什么硬件（会ttl），连接什么位置，怎么操作。。。老哥有空做一个教程吗？

**Comment by ohdarling** [comment]
1. 硬件可以进去[嘉立创开源平台 AirCube](https://oshwhub.com/wandaeda/aircube) 使用编辑器打开，然后进行 PCB 下单打样，可以领券免费
2. 按 README 中介绍的元件在淘宝上采购，包括 2.54mm 的排母，然后将排母焊接到 PCB 上
3. 软件直接使用 ESPHome，按照 ESPHome 官方文档安装命令行工具之后，clone 本项目，进入 Firmware 目录，支行 esphome run 就可以了

**Comment by SoulLinksIly** [comment]
https://github.com/SoulLinksIly/Pic/blob/master/BOM%E5%8F%8A%E9%93%BE%E6%8E%A5.xlsx
老哥，我总结了一下bom，你看各个型号啥的有没有问题，修改后可以看需不需要添加到你的嘉立创工程的附件里面

**Comment by SoulLinksIly** [comment]
对了，板子应该多厚哇？

**Comment by ohdarling** [comment]
用 1.6mm 就可以。

**Comment by ohdarling** [comment]
看了下 BOM 没啥问题，ESP32 是 30Pin 的，理论上宽度应该是合适的。

**Comment by SoulLinksIly** [comment]
ok，感谢！
